# -*- coding: utf-8 -*-
"""Copy of DM-Lab05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13wfB0xrjquXXA1hvshrVR9N77Z4yY84V

# Lab 05 - Data Mining
The goal of this lab is to preprocess a dataset to prepare it for a machine learning task.
The only libraty you can use is **pandas**.

We will be using the Titanic dataset. The goal is to predict if the person will survive or not.

### Load the dataset
"""

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/andvise/DataAnalyticsDatasets/refs/heads/main/titanic.csv')
df

"""### Encode the categorical variable into numerical
Focus on only those that you'll be using in your machine learning model
"""

# Your code here

"""### Split the dataset in 80% training and 20% test."""

# Your code here

"""### Divide the dataset between input variables (X) and output (y).
Select which columns should be kept for this particular task.

"""

# Your code here

"""### Scale the data
Create 2 versions of the datasets, one scaled with a min-max scaler and onw with a standard scaler (using only pandas).

"""

# Your code here

"""### What is the baseline for the accuracy?
What is the minimum accuracy a classifier should reach?
"""

# Your code here

"""### Create a tree classifier and check the train and test accuracy

**You can use sklearn**


"""