# -*- coding: utf-8 -*-
"""DM-Lab05-Solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13wfB0xrjquXXA1hvshrVR9N77Z4yY84V

# Lab 05 - Data Mining
The goal of this lab is to preprocess a dataset to prepare it for a machine learning task.
The only libraty you can use is **pandas**.

We will be using the Titanic dataset. The goal is to predict if the person will survive or not.

### Load the dataset
"""

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/andvise/DataAnalyticsDatasets/refs/heads/main/titanic.csv')
df

"""### Encode the categorical variable into numerical
Focus on only those that you'll be using in your machine learning model
"""

del df['PassengerId']
del df['Name']

df['Sex'] = (df['Sex'] == "male")*1

df

"""### Split the dataset in 80% training and 20% test."""

df.fillna(0, inplace=True)

df = df.sample(len(df))

train_size = int(len(df)*0.8)
df_train = df.iloc[:train_size]
df_test = df.iloc[train_size:]

print(df_train.shape)
print(df_test.shape)

df_train

"""### Divide the dataset between input variables (X) and output (y).
Select which columns should be kept for this particular task.

"""

X_train = df_train.drop('Survived', axis=1)
y_train = df_train['Survived']

X_test = df_test.drop('Survived', axis=1)
y_test = df_test['Survived']

X_train

"""### Scale the data
Create 2 versions of the datasets, one scaled with a min-max scaler and onw with a standard scaler (using only pandas).

"""

# Your code here

mins = X_train.min()
maxs = X_train.max()

for col in X_train.columns:
  X_train[col] = (X_train[col] - mins[col])/ (maxs[col] - mins[col])
  X_test[col] = (X_test[col] - mins[col])/ (maxs[col] - mins[col])

X_test.describe()

X_test

"""### What is the baseline for the accuracy?
What is the minimum accuracy a classifier should reach?
"""

1-sum(y_test == 1)/len(y_test)

"""### Create a tree classifier and check the train and test accuracy

**You can use sklearn**


"""